load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    srcs = ["editor.cpp"],
    hdrs = ["include/editor_core/editor.h"],
    strip_include_prefix = "include",
    visibility = [
        "//applications/editor:__pkg__",
        "//editor_core/tests:__pkg__",
    ],
    deps = [
        "//document:api",
        "//key:api",
    ],
)
