load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:private"])

cc_test(
    name = "decoder_tests",
    srcs = ["decoder_tests.cpp"],
    copts = ["-UNDEBUG"],
    deps = [
        "//key_decoder:api",
        "//key_decoder/ports/byte_source:api",
        "//key_decoder/ports/byte_source:conformance",
        "@googletest//:gtest_main",
    ],
)
