load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    srcs = ["src/key.cpp"],
    hdrs = ["include/key/key.h"],
    strip_include_prefix = "include",
    copts = ["-std=c++23", "-Wall", "-Wextra", "-Wpedantic", "-Werror"],
    visibility = [
        "//applications/editor:__pkg__",
        "//editor_core:__pkg__",
        "//key/tests:__pkg__",
        "//key_decoder:__pkg__",
        "//terminal:__pkg__",
    ],
)
