load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    srcs = ["decoder.cpp"],
    hdrs = ["include/key_decoder/decoder.h"],
    strip_include_prefix = "include",
    visibility = [
        "//key_decoder/tests:__pkg__",
        "//terminal:__pkg__",
    ],
    deps = [
        "//key:api",
        "//key_decoder/ports/byte_source:api",
    ],
)
