load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:private"])

COMMON_COPTS = [
    "-std=c++23",
    "-Wall",
    "-Wextra",
    "-Wpedantic",
    "-Werror",
]

cc_library(
    name = "api",
    srcs = ["decoder.cpp"],
    hdrs = ["decoder.h"],
    copts = COMMON_COPTS,
    visibility = ["//terminal:__pkg__"],
    deps = [
        "//key:api",
        "//key_decoder/ports/byte_source:api",
    ],
)

cc_test(
    name = "decoder_tests",
    srcs = ["decoder_tests.cpp"],
    copts = COMMON_COPTS + ["-UNDEBUG"],
    deps = [
        ":api",
        "//key_decoder/ports/byte_source:api",
        "//key_decoder/ports/byte_source:conformance",
        "@googletest//:gtest_main",
    ],
)
