load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    hdrs = ["size_limits.h"],
    visibility = [
        "//document:__pkg__",
        "//document/internal/size_limits/tests:__pkg__",
        "//document/internal/gap_buffer:__pkg__",
        "//document/internal/line_starts:__pkg__",
    ],
    deps = ["//document/types:api"],
)
