load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    srcs = ["load.cpp"],
    hdrs = ["include/file_loader/load.h"],
    strip_include_prefix = "include",
    visibility = [
        "//applications/editor:__pkg__",
        "//file_loader/tests:__pkg__",
    ],
    deps = ["//document/types:api"],
)
