load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    srcs = ["io.cpp"],
    hdrs = ["include/terminal_io/io.h"],
    strip_include_prefix = "include",
    visibility = [
        "//terminal:__pkg__",
        "//terminal_io/tests:__pkg__",
        "//terminal/internal/fd_byte_source:__pkg__",
    ],
)
