load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:private"])

cc_test(
    name = "syscall_tests",
    # Wrapping must resolve library syscall references in this executable.
    linkstatic = True,
    srcs = ["syscall_tests.cpp"],
    copts = ["-UNDEBUG"],
    linkopts = [
        "-Wl,--wrap=read",
        "-Wl,--wrap=write",
        "-Wl,--wrap=poll",
        "-Wl,--wrap=isatty",
    ],
    deps = [
        "//terminal_io:api",
        "@googletest//:gtest_main",
    ],
)
