load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "api",
    hdrs = ["types.h"],
    visibility = [
        "//document:__pkg__",
        "//document/internal/size_limits:__pkg__",
        "//file_loader:__pkg__",
        "//file_loader/tests:__pkg__",
    ],
)
